"""create tables

Revision ID: b44802c171aa
Revises: 51ffc092eec9
Create Date: 2025-07-03 15:11:33.935697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44802c171aa'
down_revision: Union[str, Sequence[str], None] = '51ffc092eec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('aqi_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=False),
    sa.Column('pm10', sa.Float(), nullable=False),
    sa.Column('no2', sa.Float(), nullable=False),
    sa.Column('o3', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aqi_records_id'), 'aqi_records', ['id'], unique=False)
    op.create_index(op.f('ix_aqi_records_timestamp'), 'aqi_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aqi_records_timestamp'), table_name='aqi_records')
    op.drop_index(op.f('ix_aqi_records_id'), table_name='aqi_records')
    op.drop_table('aqi_records')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
